#' Specify, Check, and Write Shocks for Modeling
#'
#' This function specifies shocks for modeling, runs a series of checks on the
#' specified variables, sets, and elements, and writes the shocks to a file. It
#' is designed to work with sets defined in the model configuration and supports
#' both intertemporal and other types of dynamics.
#'
#' @inheritParams teems_model
#' @inheritParams teems_time
#' @inheritParams teems_closure
#'
#' @importFrom rlang expr
#' @importFrom targets tar_target_raw tar_cue
#' @return A list of targets generated by the function, including specified
#'   shocks, checked shocks, and the result of writing the shocks to a file.
#' @keywords internal
#' @noRd
.shock_config <- function(shock,
                          shock_file,
                          ndigits,
                          write_dir) {

  if (!is.null(x = shock_file)) {
    t_shock_file <- rlang::expr(targets::tar_target_raw(
      name = "shock_file",
      command = quote(expr = !!shock_file),
      format = "file"
    ))
  }

  if (!is.null(x = shock)) {
  # shock files need to be tracked via targets
    t_shocks <- rlang::expr(targets::tar_target_raw(
    name = "shocks",
    command = quote(expr = !!shock),
    cue = targets::tar_cue(mode = "always")
  ))

  # run series of checks on specified variables, sets, and elements
  # currently only functional for sets defined in model config, see set expansion
    t_prepped.shocks <- rlang::expr(targets::tar_target_raw(
    name = "prepped.shocks",
    command = expression(.shock_prep(
      shocks = shocks,
      var_extract = tablo_var
    )),
    cue = targets::tar_cue(mode = "always")
  ))

    t_constructed.shocks <- rlang::expr(targets::tar_target_raw(
    name = "constructed.shocks",
    command = expression(.shock_construct(
      shock_list = prepped.shocks,
      closure = swapped.out.cls,
      var_extract = tablo_var,
      sets = final.set_tib,
      time_coeff = time_coeff
    )),
    cue = targets::tar_cue(mode = "always")
  ))
  } else {
    if (!is.null(x = shock_file)) {
      t_shocks <- rlang::expr(targets::tar_target_raw(
        name = "shocks",
        command = expression(readLines(con = shock_file)),
        cue = targets::tar_cue(mode = "always")
      ))

      t_constructed.shocks <- rlang::expr(targets::tar_target_raw(
        name = "constructed.shocks",
        command = expression({
          return(list(shocks = list(user = list(shock = shocks,
                                                type = "user")),
                      shock_file = shock_file))
        }),
        cue = targets::tar_cue(mode = "always")
      ))
    } else {
      t_constructed.shocks <- rlang::expr(targets::tar_target_raw(
      name = "constructed.shocks",
      command = expression({
        return(list(shocks = NULL,
                    shock_file = paste0(format(x = Sys.time(), "%H%M%S"),
                                        ".shf")))
      }),
      cue = targets::tar_cue(mode = "always")
    ))
    }
  }

  # Write shock(s)
  t_write.shocks <- rlang::expr(targets::tar_target_raw(
    name = "write.shocks",
    command = expression(.TEEMS_write(
      input = constructed.shocks[["shocks"]],
      ndigits = !!ndigits,
      file = constructed.shocks[["shock_file"]],
      write_object = "shk",
      write_dir = !!write_dir
    )),
    format = "file",
    cue = targets::tar_cue(mode = "always")
  ))
  ##############################################################################
  # gather and check all generated targets
  targets <- .gather_targets(criteria = "t_")
  return(targets)
}
