#' `r lifecycle::badge("experimental")`
#' Loads and execute model-specifc `targets` pipeline
#'
#' @description `ems_deploy()` creates and executes a
#'   [`targets`](https://books.ropensci.org/targets/) pipeline for all
#'   loaded specifications according to their various path
#'   dependencies. Outputs from [`ems_model()`] and [`ems_load()`],
#'   are required inputs to
#'   `"model_config"`, `"load_config"` respectively.
#'
#'
#' @param model_config A list generated by the function
#'   [`ems_model()`].
#' @param load_config A list generated by the function
#'   [`ems_load()`].
#' @param model_name Character of length 1 (default is `"teems"`),
#'   descriptive model name. This string determines the name of
#'   model-specific directory to be written within `"base_dir"` as
#'   well as the `targets` pipeline file that will be run to generate
#'   all input files. Note that to access the `targets` store for a
#'   previously established model, both the `"model_name"` and
#'   `"base_dir"` must remain constant.
#' @param base_dir Character of length 1 (default is `tempdir()`),
#'   directory where the model-specific directory and model pipeline
#'   will be written. If `tempdir()`, the `targets` store and other
#'   model-specific files and directories will not persist across R
#'   sessions. If a persistent directory is specified, some targets
#'   will not need to be rerun in successive R sessions.
#' @param .testing Logical of length 1 (default is `FALSE`), developer
#'   option. If `TRUE`, [`targets::tar_make()`] will be called with
#'   `"callr_function = NULL"`. This allows the model pipeline to be
#'   halted for debugging and/or development purposes through
#'   placement of `browser()`.
#'
#' @importFrom targets tar_load_everything
#'
#' @return File path to a CMF file necessary to execute
#'   [`ems_solve()`].
#'
#' @details `ems_deploy()` consolidates all user inputs and carries
#'   out all operations necessary to run a CGE model. The output file
#'   path serves as a required input to [`ems_solve()`].
#'
#' @seealso [`ems_model()`] for generating the input to
#'   `"model_config"`.
#' @seealso [`ems_load()`] for generating the input to
#'   `"base_config"`.
#' @seealso [`ems_solve()`] for loading the ouput of this function.
#'
#' @examples
#' \dontrun{
#' # A GTAPv6.2 3-region, 6-sector, 4-endowment static model run with
#' # numeraire shock. Note that the GTAPv7 is currently only
#' # compatible with a separate data format not available in freely
#' # distributed GTAP Databases. Future work will produce a function
#' # to utilize v6.2 data compatible with GTAPv7 and v7 compatible
#' # data with v6.2-based models.
#'
#' v6.2_model_config <- teems_model(tab_file = "GTAPv6.2",
#'                                 ndigits = 8,
#'                                 verbose = TRUE)
#'
#' v6.2_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' v6.2_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' v6.2_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                              region_mapping = "big3",
#'                              sector_mapping = "macro_sector",
#'                              endowment_mapping = "labor_agg",
#'                              verbose = TRUE)
#'
#' v6.2_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                  type = "uniform",
#'                                  value = 1)
#'
#' v6.2_closure_config <- teems_closure(shock = v6.2_numeraire_shk)
#'
#' v6.2_cmf_path <- teems_deploy(model_config = v6.2_model_config,
#'                              base_config = v6.2_base_config,
#'                              param_config = v6.2_param_config,
#'                              set_config = v6.2_set_config,
#'                              closure_config = v6.2_closure_config,
#'                              verbose = TRUE)
#'
#' # A GTAP-INTv1 3-region, 6-sector, 4-endowment, 5 timestep
#' # intertemporal model run with numeraire shock.
#' INTv1_model_config <- teems_model(tab_file = "GTAP-INTv1",
#'                                   ndigits = 8,
#'                                   verbose = TRUE)
#'
#' INTv1_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' INTv1_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' INTv1_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                                region_mapping = "big3",
#'                                sector_mapping = "macro_sector",
#'                                endowment_mapping = "labor_agg",
#'                                verbose = TRUE)
#'
#' INTv1_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                    type = "uniform",
#'                                    value = 1)
#'
#' INTv1_closure_config <- teems_closure(shock = INTv1_numeraire_shk)
#'
#' INTv1_time_config <- teems_time(time_steps = c(2011, 2012, 2015, 2020, 2030))
#'
#' INTv1_cmf_path <- teems_deploy(model_config = INTv1_model_config,
#'                                base_config = INTv1_base_config,
#'                                param_config = INTv1_param_config,
#'                                set_config = INTv1_set_config,
#'                                closure_config = INTv1_closure_config,
#'                                time_config = INTv1_time_config,
#'                                verbose = TRUE)
#'
#' # In the examples above the `targets` store and model input files
#' # will be written to a per-session temporary folder that will not
#' # persist. In order to fully take advantage of the `targets`
#' # package underpinning `teems`, `"model_name"` and `"base_dir"`
#' # arguments allow for model directories to persist across sessions.
#'
#' custom_path <- teems_deploy(model_config = INTv1_model_config,
#'                             base_config = INTv1_base_config,
#'                             param_config = INTv1_param_config,
#'                             set_config = INTv1_set_config,
#'                             closure_config = INTv1_closure_config,
#'                             time_config = INTv1_time_config,
#'                             model_name = "custom_INT",
#'                             base_dir = path.expand(path = "~"))
#'
#' # Example: Pre-model run directory layout assuming path.expand("~")
#' # evaluates to /home/user
#' # Any of the objects above in (/home/user/custom_INT/store/objects)
#' # can be inspected using [`targets::tar_read()`]. For example, the
#' # final model closure:
#' targets::tar_read(name = final.closure,
#'                   store = "/home/user/custom_INT/store")
#' }
#' @export
ems_deploy <- function(model_config,
                       load_config,
                       model_name = "teems",
                       base_dir = tempdir(),
                       #tar_load_everything = FALSE,
                       .testing = FALSE)
{
if (missing(model_config)) {.cli_missing(model_config)}
if (missing(load_config)) {.cli_missing(load_config)}
call <- match.call()
args_list <- mget(x = names(x = formals()))
# check for missing arguments here (across inputs)
teems_paths <- .path_ledger(base_dir = base_dir,
                            model_name = model_name,
                            call)
# int_data <- .get_int_data(aux_data = data_specs[["aux_input"]],
#                           intertemporal = model_specs[["intertemporal"]])
targets <- .write_pipeline(model_config = model_config,
                           load_config = load_config,
                           model_name = model_name,
                           set_map_files = set_map_files,
                           metadata = load_config$metadata,
                           teems_paths = teems_paths)
call_hash_tbl <- .hash_table(model_config = model_config,
                             load_config = load_config)
.execute_pipeline(teems_paths = teems_paths,
                  call_hash_tbl = call_hash_tbl,
                  #tar_load_everything = tar_load_everything,
                  .testing = .testing)
# if (tar_load_everything) {
#   targets::tar_load_everything(store = teems_paths[["store"]],
#                                envir = .GlobalEnv)
# }
coefficient_names <- .process_tablo(tab_file = model_specs[["tab_file"]],
                                    type = "coefficient")[["coefficient"]]
gen_out <- .write_cmf(model_name = model_name,
                      coefficient_names = coefficient_names,
                      model_dir = teems_paths[["model"]],
                      store_dir = teems_paths[["store"]],
                      launchpad_dir = teems_paths[["launchpad"]])
.pipeline_diagnostics(model_dir = teems_paths[["model"]],
                      launchpad_dir = teems_paths[["launchpad"]],
                      model_name = model_name,
                      metadata = load_specs[["metadata"]],
                      store_dir = teems_paths[["store"]],
                      io_files = gen_out[["io_files"]])
cmf_path <- gen_out[["cmf_path"]]
class(cmf_path) <- "cmf"
cmf_path
}
