#' Load general model specifications
#'
#' @description `ems_model()` loads general model specifications, conducts
#'   pre-pipeline checks, and determines temporal dynamics. The output of this
#'   function is a required input to the `"model_config"` argument within the
#'   [`ems_deploy()`] function.
#'
#' @param tab_file Character of length 1, path to a local Tablo model file or
#'   selection of an internal Tablo file. Currently supported internal Tablo
#'   model files can be viewed with ().
#' @param var_omit A character vector (default is `NULL`). Variables to be
#'   removed from the Tablo model file as well as from the designated closure
#'   (if present).
#' @param closure_file A character of length 1 (default is `NULL`). File name in
#'   working directory or path to a ".cls" closure file.
#' @param swap_in Character vector (default is `NULL`), or `swap` object created
#'   by [`ems_swap()`], or a list of any combination of character vectors and
#'   swap objects. Represents model variable or variables to be made exogenous.
#' @param swap_out Character vector (default is `NULL`), or `swap` object
#'   created by [`ems_swap()`], or a list of any combination of character
#'   vectors and swap objects. Represents model variable or variables to be made
#'   endogenous.
#' @param shock_file Character of length 1, file name in working directory or
#'   path to a csv representing the final shock file. No checks or modifications
#'   will be conducted on this file.
#' @param shock A `shock` object or in the case of multiple shocks, list of
#'   objects produced by [`ems_shock()`] (default is `NULL`). In the case of
#'   `NULL`, a `NULL` shock will be carried out which effectively returns the
#'   base data.
#' @param notes Character string (default is `NULL`). If not `NULL` notes will
#'   be written to a .txt file within the model-specific directory generated by
#'   [`ems_deploy()`].
#'
#' @return A list of general model configuration options to be passed to the
#'   `model_config` argument of [`ems_deploy()`].
#'
#' @details `ems_model()` return values have no purpose used in isolation and
#'   are rather combined with user inputs in other `teems` package functions
#'   within [`ems_deploy()`] to produce a path-dependent pipeline resulting in
#'   solver-ready input files for [`ems_solve()`].
#'
#' @seealso [`ems_swap()`] for loading both full variable swaps as well as
#'   element-specific swaps.
#' @seealso [`ems_shock()`] for loading a variety of shock types.
#' @seealso [`ems_deploy()`] for loading the output of this function.
#'
#' @examples
#' # Simple swap and shock
#' # numeraire shock
#' numeraire_shock <- ems_shock(var = "pfactwld",
#'                              type = "uniform",
#'                              value = 0.5)
#' # internal Tablo file "GTAPv7.0" with standard variable omissions and 
#' # standard closure implicitly selected
#' ems_model(tab_file = "GTAPv7.0", 
#'           var_omit = c("atall", "avaall", "tfe", "tfd", "tfm", "tgd", "tgm", 
#'                        "tpdall", "tpmall", "tid", "tim"),
#'           shock = numeraire_shock)
#'             
#' # Mixed multiple swaps and shocks
#' qfd_shk <- ems_shock(var = "qfd",
#'                      type = "uniform",
#'                      input = 1,
#'                      REGr = "lam",
#'                      ACTSa = "crops")
#' 
#' yp_in <- ems_swap(var = "yp")
#' dppriv_out <- ems_swap(var = "dppriv")
#' 
#' yp_shk <- ems_shock(var = "yp",
#'                     type = "uniform",
#'                     input = 1)
#' 
#' ems_model(
#'   tab_file = "GTAP-REv1",
#'   var_omit = c(
#'     "atall",
#'     "avaall",
#'     "tfe",
#'     "tfm",
#'     "tgd",
#'     "tgm",
#'     "tid",
#'     "tim"
#'   ),
#'   shock = list(qfd_shk, yp_shk),
#'   swap_in = list("qfd", yp_in),
#'   swap_out = list("tfd", dppriv_out)
#' )
#'             
#' @export
ems_model <- function(tab_file,
                      var_omit = NULL)
{
  # add "auto_omit" arg and other substitution/replacement options
if (missing(tab_file)) {.cli_missing(tab_file)}
args_list <- mget(names(formals()))
call <- match.call()
v <- .validate_model_args(a = args_list,
                          call = call)
model <- .process_tablo(tab_file = v$tab_file,
                        var_omit = v$var_omit,
                        call = call)
model
}
