#' `r lifecycle::badge("experimental")` Load data specifications
#'
#' @description `ems_load()` loads coefficient data including
#'   base data, parameters, and any auxillary data as well as
#'   conducts pre-pipleine checks. The output of this function is
#'   a required input to the `"load_config"` argument within the
#'   [`ems_deploy()`] function.
#'
#' @param ems_input Master input generated by [`ems_data()`].
#' @param dat_input Input containing base coefficient data.
#'   * Character of length 1, file name in working directory or path
#'   to a GTAP data "dat" HAR file.
#'   * Equivalent list object generated by [`ems_data()`].
#' @param par_input Input containing parameter coefficient data.
#'   Character of length 1, file name in working directory or
#'   path to a GTAP parameter "par" HAR file.
#'   * Equivalent list object generated by [`ems_data()`].
#' @param aux_input Input containing auxillary coefficient data.
#'   Currently used primarily to load time related data for
#'   dynamic models.
#'   * Character of length 1, file name in working directory or path
#'   to a GTAP HAR file.
#'   * Equivalent list object generated by [`ems_data()`].
#' @param unaggregated_input A named list (default is `NULL`).
#'   Key-value pairs denoting the name of the header to replace
#'   and path to a CSV file or data frame or data frame extension
#'   containing data. User-provided data must contain all
#'   corresponding sets and associated elements present in the
#'   original header data as well as a "Value" column with new
#'   values. This replacement will be subject to structure checks
#'   and set aggregations.
#' @param aggregated_input A named list (default is `NULL`).
#'   Key-value pairs denoting the name of the header to replace
#'   and path to a CSV file or data frame or data frame extension
#'   containing data. A length 1 numeric may be provided for
#'   coefficents with no set affiliations (e.g., binary
#'   switches). User-provided data must contain all set
#'   aggregation-specific elements to be replaced as well as a
#'   "Value" column with new values. This replacement will be
#'   subject to structure checks according to selected set
#'   aggregations.
#' @param ... A named pairlist assigning either externally
#'   provided mappings (path to CSV) or internally available
#'   mappings to model sets that are read in (not constructed via
#'   any operation).
#'
#' @return A list of data configuration options.
#'
#' @details `ems_load()` return values have no purpose used in
#'   isolation and are rather combined with user inputs in other
#'   `teems` package functions within [`ems_deploy()`] to produce
#'   a path-dependent pipeline resulting in solver-ready input
#'   files for [`ems_solve()`].
#'
#' @seealso [`ems_deploy()`] for loading the output of this
#'   function.
#'
#'
#' @examples
#' \dontrun{
#' # GTAP 11 data for the standard GTAP model
#' ems_load(dat_input = "your/local/path/flexAgg11c17/gsdfdat.har",
#'          par_input = "your/local/path/flexAgg11c17/gsdfpar.har",
#'          set_input = "your/local/path/flexAgg11c17/gsdfset.har",
#'          REG = "AR5",
#'          COMM = "macro_sector",
#'          ACTS = "macro_sector",
#'          ENDW = "labor_agg")
#'
#' # GTAP 10 data for the classic GTAP model
#' ems_load(dat_input = "your/local/path/flexagg10AY14/gsddat.har",
#'          par_input = "your/local/path/flexagg10AY14/gsdpar.har",
#'          set_input = "your/local/path/flexagg10AY14/gsdset.har",
#'          REG = "AR5",
#'          TRAD_COMM = "macro_sector",
#'          ENDW_COMM = "labor_agg")
#'
#' # GTAP 11 data for the classic GTAP model
#' v62_data <- ems_data(dat_input = "path/to/v7_data/v11c/flexAgg11c17/gsdfdat.har",
#'                      par_input = "path/to/v7_data/v11c/flexAgg11c17/gsdfpar.har",
#'                      set_input = "path/to/v7_data/v11c/flexAgg11c17/gsdfset.har",
#'                      tab_file = "GTAPv6.2",
#'                      target_format = "v6.2")
#'
#' ems_load(ems_input = v62_data,
#'          REG = "WB7",
#'          TRAD_COMM = "agriculture",
#'          ENDW_COMM = "labor_diff")
#'
#' # Unaggregated inputs
#' # These inputs must contain all tuples of the data that it is to
#' # replace as per the database in use, plus a `Value` column.
#' ETRAE <- data.frame(
#'   ENDW_COMMi = c("ag_othlowsk",
#'   "capital",
#'   "clerks",
#'   "land",
#'   "natlres",
#'   "off_mgr_pros",
#'   "service_shop",
#'   "tech_aspros"),
#'   Value = c(0, 0, 0, -1, -0.002, 0, 0))
#'
#' ems_load(dat_input = "your/local/path/flexagg10AY14/gsddat.har",
#'          par_input = "your/local/path/flexagg10AY14/gsdpar.har",
#'          set_input = "your/local/path/flexagg10AY14/gsdset.har",
#'          unaggregated_input = ETRAE)
#'
#' # Aggregated inputs
#' # These inputs must contain all tuples of the data that it is to
#' # replace as per selected set aggregations, plus a `Value` column.
#' ETRAE <- expand.grid(ENDWe = c("capital", "labor", "land", "natlres"),
#'                      REGr = c("chn", "row", "usa"))
#' ETRAE$Value <- rep(c(0, 0, -1, -0.002), 3)
#'
#' ems_load(dat_input = "your/local/path/flexAgg11c17/gsdfdat.har",
#'          par_input = "your/local/path/flexAgg11c17/gsdfpar.har",
#'          set_input = "your/local/path/flexAgg11c17/gsdfset.har",
#'          aggregated_input = list(ETRE = ETRAE,
#'                                  RDLT = 0))
#' }
#' @export
ems_load <- function(ems_input,
                     dat_input = NULL,
                     par_input = NULL,
                     set_input = NULL,
                     aux_input = NULL,
                     unaggregated_input = NULL,
                     aggregated_input = NULL,
                     ...)
{
args_list <- mget(names(formals()))
if (missing(ems_input)) {args_list$ems_input <- NULL}
args_list$set_mappings <- list(...)
args_list$... <- NULL
call <- match.call()
config <- .validate_load_args(args_list = args_list,
                              call = call)
config
}
