#' Loads all specifications executes a model-specifc `targets`
#' pipeline
#'
#' @description `teems_deploy()` creates and executes a
#'   [`targets`](https://books.ropensci.org/targets/) pipeline for all
#'   loaded specifications according to their various path
#'   dependencies. Outputs from [`teems_model()`], [`teems_base()`],
#'   [`teems_param()`], and [`teems_sets()`] are required inputs to
#'   `"model_config"`, `"base_config"`, `"param_config"`, and
#'   `"set_config"` respectively.
#'
#'   Learn more about this function including Tablo file limitations
#'   in `vignette("something")`
#'
#' @inheritParams teems_model
#'
#' @param model_config A list generated by the function
#'   [`teems_model()`].
#' @param base_config A list generated by the function
#'   [`teems_base()`].
#' @param param_config A list generated by the function
#'   [`teems_param()`].
#' @param set_config A list generated by the function
#'   [`teems_sets()`].
#' @param closure_config A list generated by the function
#'   [`teems_closure()`] (default is `NULL`). If `NULL`, a NULL shock
#'   will be executed on the standard closure, effectively returning
#'   the base data. This can be useful for testing purposes or to
#'   return all model coefficient values at the current reference
#'   year.
#' @param time_config A list generated by the function
#'   [`teems_time()`] (default is `NULL`). This argument is only
#'   required in the case of non-static model runs.
#' @param model_name Character of length 1 (default is `"teems"`),
#'   descriptive model name. This string determines the name of
#'   model-specific directory to be written within `"base_dir"` as
#'   well as the `targets` pipeline file that will be run to generate
#'   all input files. Note that to access the `targets` store for a
#'   previously established model, both the `"model_name"` and
#'   `"base_dir"` must remain constant.
#' @param base_dir Character of length 1 (default is `tempdir()`),
#'   directory where the model-specific directory and model pipeline
#'   will be written. If `tempdir()`, the `targets` store and other
#'   model-specific files and directories will not persist across R
#'   sessions. If a persistent directory is specified, some targets
#'   will not need to be rerun in successive R sessions.
#' @param .testing Logical of length 1 (default is `FALSE`), developer
#'   option. If `TRUE`, [`targets::tar_make()`] will be called with
#'   `"callr_function = NULL"`. This allows the model pipeline to be
#'   halted for debugging and/or development purposes through
#'   placement of `browser()`.
#'
#' @importFrom targets tar_load_everything
#'
#' @return File path to a CMF file necessary to execute
#'   [`teems_solve()`].
#'
#' @details `teems_deploy()` consolidates all user inputs and carries
#'   out all operations necessary to run a CGE model. The output file
#'   path serves as a required input to [`teems_solve()`].
#'
#' @seealso [`teems_model()`] for generating the input to
#'   `"model_config"`.
#' @seealso [`teems_base()`] for generating the input to
#'   `"base_config"`.
#' @seealso [`teems_param()`] for generating the input to
#'   `"param_config"`.
#' @seealso [`teems_sets()`] for generating the input to
#'   `"set_config"`.
#' @seealso [`teems_closure()`] for generating the input to
#'   `"closure_config"`.
#' @seealso [`teems_time()`] for generating the input to
#'   `"time_config"`.
#' @seealso [`teems_solve()`] for loading the ouput of this function.
#'
#' @examples
#' \dontrun{
#' # A GTAPv6.2 3-region, 6-sector, 4-endowment static model run with
#' # numeraire shock. Note that the GTAPv7 is currently only
#' # compatible with a separate data format not available in freely
#' # distributed GTAP Databases. Future work will produce a function
#' # to utilize v6.2 data compatible with GTAPv7 and v7 compatible
#' # data with v6.2-based models.
#'
#' v6.2_model_config <- teems_model(tab_file = "GTAPv6.2",
#'                                 ndigits = 8,
#'                                 verbose = TRUE)
#'
#' v6.2_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' v6.2_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' v6.2_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                              region_mapping = "big3",
#'                              sector_mapping = "macro_sector",
#'                              endowment_mapping = "labor_agg",
#'                              verbose = TRUE)
#'
#' v6.2_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                  type = "uniform",
#'                                  value = 1)
#'
#' v6.2_closure_config <- teems_closure(shock = v6.2_numeraire_shk)
#'
#' v6.2_cmf_path <- teems_deploy(model_config = v6.2_model_config,
#'                              base_config = v6.2_base_config,
#'                              param_config = v6.2_param_config,
#'                              set_config = v6.2_set_config,
#'                              closure_config = v6.2_closure_config,
#'                              verbose = TRUE)
#'
#' # A GTAP-INTv1 3-region, 6-sector, 4-endowment, 5 timestep
#' # intertemporal model run with numeraire shock.
#' INTv1_model_config <- teems_model(tab_file = "GTAP-INTv1",
#'                                   ndigits = 8,
#'                                   verbose = TRUE)
#'
#' INTv1_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' INTv1_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' INTv1_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                                region_mapping = "big3",
#'                                sector_mapping = "macro_sector",
#'                                endowment_mapping = "labor_agg",
#'                                verbose = TRUE)
#'
#' INTv1_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                    type = "uniform",
#'                                    value = 1)
#'
#' INTv1_closure_config <- teems_closure(shock = INTv1_numeraire_shk)
#'
#' INTv1_time_config <- teems_time(time_steps = c(2011, 2012, 2015, 2020, 2030))
#'
#' INTv1_cmf_path <- teems_deploy(model_config = INTv1_model_config,
#'                                base_config = INTv1_base_config,
#'                                param_config = INTv1_param_config,
#'                                set_config = INTv1_set_config,
#'                                closure_config = INTv1_closure_config,
#'                                time_config = INTv1_time_config,
#'                                verbose = TRUE)
#'
#' # In the examples above the `targets` store and model input files
#' # will be written to a per-session temporary folder that will not
#' # persist. In order to fully take advantage of the `targets`
#' # package underpinning `teems`, `"model_name"` and `"base_dir"`
#' # arguments allow for model directories to persist across sessions.
#'
#' custom_path <- teems_deploy(model_config = INTv1_model_config,
#'                             base_config = INTv1_base_config,
#'                             param_config = INTv1_param_config,
#'                             set_config = INTv1_set_config,
#'                             closure_config = INTv1_closure_config,
#'                             time_config = INTv1_time_config,
#'                             model_name = "custom_INT",
#'                             base_dir = path.expand(path = "~"))
#'
#' # Example: Pre-model run directory layout assuming path.expand("~")
#' # evaluates to /home/user
#' # Any of the objects above in (/home/user/custom_INT/store/objects)
#' # can be inspected using [`targets::tar_read()`]. For example, the
#' # final model closure:
#' targets::tar_read(name = final.closure,
#'                   store = "/home/user/custom_INT/store")
#' }
#' @export
teems_deploy <- function(model_config,
                         data_config,
                         set_config,
                         model_name = "teems",
                         base_dir = tempdir(),
                         quiet = FALSE,
                         tar_load_everything = FALSE,
                         tar_visnetwork = FALSE,
                         .testing = FALSE)
{
call <- match.call()
args_list <- mget(x = names(x = formals()))
# check for missing arguments here (across inputs)
teems_paths <- .path_ledger(base_dir = base_dir,
                            model_name = model_name,
                            call)
n_timestep <- .get_timesteps(aux_data = data_specs[["aux_input"]],
                             intertemporal = model_specs[["intertemporal"]])
set_map_files <- .get_setmap_info(config = set_specs)
shock_config <- model_config["shock"]
shock_call <- purrr::pluck(.x = shock_config, "shock", "call")
shock_config[["shock"]][["call"]] <- NULL
targets <- .write_pipeline(model_config = model_config,
                           data_config = data_config,
                           set_config = set_config,
                           shock_config = shock_config,
                           shock_call = shock_call,
                           model_name = model_name,
                           n_timestep = n_timestep,
                           set_map_files = set_map_files,
                           metadata = data_specs[["metadata"]],
                           teems_paths = teems_paths)
.execute_pipeline(teems_paths = teems_paths,
                  model_call = model_config[["call"]],
                  data_call = data_config[["call"]],
                  set_call = set_config[["call"]],
                  shock_call = shock_call,
                  tar_load_everything = tar_load_everything,
                  .testing = .testing)
if (tar_load_everything) {
  targets::tar_load_everything(store = teems_paths[["store"]],
                               envir = .GlobalEnv)
}
coefficient_names <- .process_tablo(tab_file = model_specs[["tab_file"]],
                                    type = "coefficient")[["coefficient"]]
gen_out <- .write_cmf(model_name = model_name,
                      coefficient_names = coefficient_names,
                      model_dir = teems_paths[["model"]],
                      store_dir = teems_paths[["store"]],
                      launchpad_dir = teems_paths[["launchpad"]])
.pipeline_diagnostics(model_dir = teems_paths[["model"]],
                      launchpad_dir = teems_paths[["launchpad"]],
                      model_name = model_name,
                      metadata = data_specs[["metadata"]],
                      store_dir = teems_paths[["store"]],
                      io_files = gen_out[["io_files"]],
                      quiet = quiet)
gen_out[["cmf_path"]]
}
