#' Load general model specifications
#'
#' @description `teems_model()` loads general model specifications, conducts
#'   pre-pipeline checks, and determines temporal dynamics. The output of this
#'   function is a required input to the `"model_config"` argument within the
#'   [`teems_deploy()`] function.
#'
#'   Learn more about this function including Tablo file limitations in
#'   `vignette("something")`
#'
#' @param tab_file Character of length 1, path to a local Tablo model file or
#'   selection of an internal Tablo file. Currently supported internal Tablo
#'   model files can be viewed with ().
#' @param var_omit A character vector (default is `NULL`). Variables to be
#'   removed from the Tablo model file as well as from the designated closure
#'   (if present).
#' @param closure_file A character of length 1 (default is `NULL`). File name in
#'   working directory or path to a ".cls" closure file.
#' @param swap_in Character vector (default is `NULL`), or `swap` object created
#'   by [`teems_swap()`], or a list of any combination of character vectors and
#'   swap objects. Represents model variable or variables to be made exogenous.
#' @param swap_out Character vector (default is `NULL`), or `swap` object
#'   created by [`teems_swap()`], or a list of any combination of character
#'   vectors and swap objects. Represents model variable or variables to be made
#'   endogenous.
#' @param shock_file Character of length 1, file name in working directory or
#'   path to a csv representing the final shock file. No checks or modifications
#'   will be conducted on this file.
#' @param shock A `shock` object or in the case of multiple shocks, list of
#'   objects produced by [`teems_shock()`] (default is `NULL`). In the case of
#'   `NULL`, a `NULL` shock will be carried out which effectively returns the
#'   base data.
#' @param ndigits Integer (default is `6`). Exact number of digits to the right
#'   of the decimal point to be written to file for numeric type double (GEMPack
#'   equivalent "real"). This value is passed to the `format()` nsmall argument
#'   and `round()` digits argument.
#' @param full_exclude A character vector (default is `c("DREL", "DVER", "XXCR",
#'   "XXCD", "XXCP", "SLUG", "EFLG")`). Specifies headers to fully exclude from
#'   all aspects of the model run. Failure to designate these headers properly
#'   will result in errors because some headers cannot be aggregated or mapped.
#'   Modify with caution.
#' @param notes Character string (default is `NULL`). If not `NULL` notes will
#'   be written to a .txt file within the model-specific directory generated by
#'   [`teems_deploy()`].
#' @param quiet Logical of length 1 (default is `FALSE`). If `TRUE`,
#'   function-specific diagnostics are silenced.
#'
#' @return A list of general model configuration options to be passed to the
#'   `model_config` argument of [`teems_deploy()`].
#'
#' @details `teems_model()` return values have no purpose used in isolation and
#'   are rather combined with user inputs in other `teems` package functions
#'   within [`teems_deploy()`] to produce a path-dependent pipeline resulting in
#'   solver-ready input files for [`teems_solve()`].
#'
#' @seealso [`teems_swap()`] for loading both full variable swaps as well as
#'   element-specific swaps.
#' @seealso [`teems_shock()`] for loading a variety of shock types.
#' @seealso [`teems_deploy()`] for loading the output of this function.
#'
#' @examples
#' # Simple swap and shock
#' # numeraire shock
#' numeraire_shock <- teems_shock(var = "pfactwld",
#'                                type = "uniform",
#'                                value = 0.5)
#' # internal Tablo file "GTAPv7.0" with standard variable omissions and 
#' # standard closure implicitly selected
#' teems_model(tab_file = "GTAPv7.0", 
#'             var_omit = c("atall", "avaall", "tfe", "tfd", "tfm", "tgd", "tgm", 
#'                          "tpdall", "tpmall", "tid", "tim"),
#'             shock = numeraire_shock)
#'             
#' # Mixed multiple swaps and shocks
#' lam_qgdp <- teems_swap(var = "qgdp", 
#'                        REGr = "lam")
#' lam_aoreg <- teems_swap(var = "aoreg",
#'                         REGr = "lam")
#' lam_qgdp_shock <- teems_shock(var = "qgdp",
#'                               REGr = "lam",
#'                               type = "uniform",
#'                               value = 2)
#' y_shock <- teems_shock(var = "y",
#'                        type = "uniform",
#'                        value = 1.5)
#' teems_model(tab_file = "GTAP-INTv1",
#'             var_omit = c("atall", "tfd", "avaall", "tf", "tfm",
#'                          "tgd", "tgm", "tpd", "tpm"),
#'             swap_in = list(lam_qgdp, "y"),
#'             swap_out = list(lam_aoreg, "incomeslack"),
#'             shock = list(lam_qgdp_shock, y_shock))
#'             
#' @export
teems_model <- function(tab_file,
                        var_omit = NULL,
                        closure_file = NULL,
                        swap_in = NULL,
                        swap_out = NULL,
                        shock_file = NULL,
                        shock = NULL,
                        full_exclude = c("DREL", "DVER", "XXCR", "XXCD", "XXCP", "SLUG", "EFLG"),
                        notes = NULL)
{
if (missing(tab_file)) {.cli_missing(tab_file)}
args_list <- mget(names(formals()))
call <- match.call()
config <- .validate_model_args(args_list = args_list,
                               call = call)
config
}
