#' Loads all specifications executes a model-specifc `targets`
#' pipeline
#'
#' @description `teems_deploy()` creates and executes a
#'   [`targets`](https://books.ropensci.org/targets/) pipeline for all
#'   loaded specifications according to their various path
#'   dependencies. Outputs from [`teems_model()`], [`teems_base()`],
#'   [`teems_param()`], and [`teems_sets()`] are required inputs to
#'   `"model_config"`, `"base_config"`, `"param_config"`, and
#'   `"set_config"` respectively.
#'
#'   Learn more about this function including Tablo file limitations
#'   in `vignette("something")`
#'
#' @inheritParams teems_model
#'
#' @param model_config A list generated by the function
#'   [`teems_model()`].
#' @param base_config A list generated by the function
#'   [`teems_base()`].
#' @param param_config A list generated by the function
#'   [`teems_param()`].
#' @param set_config A list generated by the function
#'   [`teems_sets()`].
#' @param closure_config A list generated by the function
#'   [`teems_closure()`] (default is `NULL`). If `NULL`, a NULL shock
#'   will be executed on the standard closure, effectively returning
#'   the base data. This can be useful for testing purposes or to
#'   return all model coefficient values at the current reference
#'   year.
#' @param time_config A list generated by the function
#'   [`teems_time()`] (default is `NULL`). This argument is only
#'   required in the case of non-static model runs.
#' @param model_name Character of length 1 (default is `"teems"`),
#'   descriptive model name. This string determines the name of
#'   model-specific directory to be written within `"base_dir"` as
#'   well as the `targets` pipeline file that will be run to generate
#'   all input files. Note that to access the `targets` store for a
#'   previously established model, both the `"model_name"` and
#'   `"base_dir"` must remain constant.
#' @param base_dir Character of length 1 (default is `tempdir()`),
#'   directory where the model-specific directory and model pipeline
#'   will be written. If `tempdir()`, the `targets` store and other
#'   model-specific files and directories will not persist across R
#'   sessions. If a persistent directory is specified, some targets
#'   will not need to be rerun in successive R sessions.
#' @param .testing Logical of length 1 (default is `FALSE`), developer
#'   option. If `TRUE`, [`targets::tar_make()`] will be called with
#'   `"callr_function = NULL"`. This allows the model pipeline to be
#'   halted for debugging and/or development purposes through
#'   placement of `browser()`.
#'
#' @importFrom targets tar_helper tar_option_set tar_make tar_config_set
#' @importFrom qs2 qs_save qs_read
#'
#' @return File path to a CMF file necessary to execute
#'   [`teems_solve()`].
#'
#' @details `teems_deploy()` consolidates all user inputs and carries
#'   out all operations necessary to run a CGE model. The output file
#'   path serves as a required input to [`teems_solve()`].
#'
#' @seealso [`teems_model()`] for generating the input to
#'   `"model_config"`.
#' @seealso [`teems_base()`] for generating the input to
#'   `"base_config"`.
#' @seealso [`teems_param()`] for generating the input to
#'   `"param_config"`.
#' @seealso [`teems_sets()`] for generating the input to
#'   `"set_config"`.
#' @seealso [`teems_closure()`] for generating the input to
#'   `"closure_config"`.
#' @seealso [`teems_time()`] for generating the input to
#'   `"time_config"`.
#' @seealso [`teems_solve()`] for loading the ouput of this function.
#'
#' @examples
#' \dontrun{
#' # A GTAPv6.2 3-region, 6-sector, 4-endowment static model run with
#' # numeraire shock. Note that the GTAPv7 is currently only
#' # compatible with a separate data format not available in freely
#' # distributed GTAP Databases. Future work will produce a function
#' # to utilize v6.2 data compatible with GTAPv7 and v7 compatible
#' # data with v6.2-based models.
#'
#' v6.2_model_config <- teems_model(tab_file = "GTAPv6.2",
#'                                 ndigits = 8,
#'                                 verbose = TRUE)
#'
#' v6.2_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' v6.2_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' v6.2_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                              region_mapping = "big3",
#'                              sector_mapping = "macro_sector",
#'                              endowment_mapping = "labor_agg",
#'                              verbose = TRUE)
#'
#' v6.2_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                  type = "uniform",
#'                                  value = 1)
#'
#' v6.2_closure_config <- teems_closure(shock = v6.2_numeraire_shk)
#'
#' v6.2_cmf_path <- teems_deploy(model_config = v6.2_model_config,
#'                              base_config = v6.2_base_config,
#'                              param_config = v6.2_param_config,
#'                              set_config = v6.2_set_config,
#'                              closure_config = v6.2_closure_config,
#'                              verbose = TRUE)
#'
#' # A GTAP-INTv1 3-region, 6-sector, 4-endowment, 5 timestep
#' # intertemporal model run with numeraire shock.
#' INTv1_model_config <- teems_model(tab_file = "GTAP-INTv1",
#'                                   ndigits = 8,
#'                                   verbose = TRUE)
#'
#' INTv1_base_config <- teems_base(base_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' INTv1_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' INTv1_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                                region_mapping = "big3",
#'                                sector_mapping = "macro_sector",
#'                                endowment_mapping = "labor_agg",
#'                                verbose = TRUE)
#'
#' INTv1_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                    type = "uniform",
#'                                    value = 1)
#'
#' INTv1_closure_config <- teems_closure(shock = INTv1_numeraire_shk)
#'
#' INTv1_time_config <- teems_time(time_steps = c(2011, 2012, 2015, 2020, 2030))
#'
#' INTv1_cmf_path <- teems_deploy(model_config = INTv1_model_config,
#'                                base_config = INTv1_base_config,
#'                                param_config = INTv1_param_config,
#'                                set_config = INTv1_set_config,
#'                                closure_config = INTv1_closure_config,
#'                                time_config = INTv1_time_config,
#'                                verbose = TRUE)
#'
#' # In the examples above the `targets` store and model input files
#' # will be written to a per-session temporary folder that will not
#' # persist. In order to fully take advantage of the `targets`
#' # package underpinning `teems`, `"model_name"` and `"base_dir"`
#' # arguments allow for model directories to persist across sessions.
#'
#' custom_path <- teems_deploy(model_config = INTv1_model_config,
#'                             base_config = INTv1_base_config,
#'                             param_config = INTv1_param_config,
#'                             set_config = INTv1_set_config,
#'                             closure_config = INTv1_closure_config,
#'                             time_config = INTv1_time_config,
#'                             model_name = "custom_INT",
#'                             base_dir = path.expand(path = "~"))
#'
#' # Example: Pre-model run directory layout assuming path.expand("~")
#' # evaluates to /home/user
#'
#' #/home/user/custom_INT/
#' #├── custom_INT.R
#' #├── launchpad/
#' #│   ├── basedata.csv
#' #│   ├── custom_INT.cls
#' #│   ├── custom_INT.cmf
#' #│   ├── GTAP-INTv1.tab
#' #│   ├── int_parameters.csv
#' #│   ├── model_diagnostics.txt
#' #│   ├── out/
#' #│   │   ├── coefficients
#' #│   │   ├── variables/
#' #│   │       ├── bin
#' #│   ├── parameters.csv
#' #│   ├── pfa_140725.shf
#' #│   ├── sets.csv
#' #│   ├── time_data.csv
#' #├── store/
#' #│   ├── meta/
#' #│   │   ├── meta
#' #│   │   ├── process
#' #│   │   ├── progress
#' #│   ├── objects/
#' #│   │   ├── base_array
#' #│   │   ├── checked.closure
#' #│   │   ├── checked.set_mappings
#' #│   │   ├── closure
#' #│   │   ├── constructed.shocks
#' #│   │   ├── core_read_files
#' #│   │   ├── CPHI
#' #│   │   ├── endowment_mapping
#' #│   │   ├── expanded.closure
#' #│   │   ├── final.base_tib
#' #│   │   ├── final.closure
#' #│   │   ├── final.par_tib
#' #│   │   ├── final.set_tib
#' #│   │   ├── final.tablo
#' #│   │   ├── init.base_tib
#' #│   │   ├── init.par_tib
#' #│   │   ├── init.set_tib
#' #│   │   ├── int_param
#' #│   │   ├── int_read_files
#' #│   │   ├── internal_tab_file
#' #│   │   ├── KAPPA
#' #│   │   ├── LRORG
#' #│   │   ├── ls_dat
#' #│   │   ├── ls_par
#' #│   │   ├── ls_set
#' #│   │   ├── metadata
#' #│   │   ├── par_array
#' #│   │   ├── parsed.tablo
#' #│   │   ├── precheck.set_mappings
#' #│   │   ├── prepped.base_tib
#' #│   │   ├── prepped.par_tib
#' #│   │   ├── prepped.shocks
#' #│   │   ├── read_files
#' #│   │   ├── region_mapping
#' #│   │   ├── sector_mapping
#' #│   │   ├── set_array
#' #│   │   ├── set_mappings
#' #│   │   ├── shocks
#' #│   │   ├── swap_in
#' #│   │   ├── swap_out
#' #│   │   ├── swapped.in.cls
#' #│   │   ├── swapped.out.cls
#' #│   │   ├── tab_file_check
#' #│   │   ├── tablo_coeff
#' #│   │   ├── tablo_files
#' #│   │   ├── tablo_sets
#' #│   │   ├── tablo_var
#' #│   │   ├── time_coeff
#' #│   │   ├── time_sets
#' #│   │   ├── weighted.par_tib
#' #│   ├── user
#'
#' # Any of the objects above in (/home/user/custom_INT/store/objects)
#' # can be inspected using [`targets::tar_read()`]. For example, the
#' # final model closure:
#' targets::tar_read(name = final.closure,
#'                   store = "/home/user/custom_INT/store")
#' }
#' @export
teems_deploy <- function(model_config,
                         base_config,
                         param_config,
                         set_config,
                         closure_config = NULL,
                         model_name = "teems",
                         base_dir = tempdir(),
                         quiet = FALSE,
                         tar_load_everything = FALSE,
                         tar_visnetwork = FALSE,
                         .testing = FALSE)
{
call <- match.call()
args_list <- mget(x = names(x = formals()))
.check_missing_args(call = call,
                    args_list = args_list)
teems_paths <- .path_ledger(base_dir = base_dir,
                            model_name = model_name,
                            call)
closure_config <- .assert_config(model_config = model_config,
                                 set_config = set_config,
                                 closure_config = closure_config,
                                 base_dir = teems_paths[["base"]],
                                 store_dir = teems_paths[["store"]],
                                 model_name = model_name,
                                 call = set_config[["call"]],
                                 quiet = quiet)
metadata <- .get_metadata(con = base_config[["base_har"]],
                          model = model_config[["model_version"]])
targets <- .write_pipeline(model_config = model_config,
                           base_config = base_config,
                           param_config = param_config,
                           set_config = set_config,
                           closure_config = closure_config,
                           shock_config = shock_config,
                           metadata = metadata,
                           teems_paths = teems_paths)
cmf_path  <- .execute_pipeline(teems_paths = teems_paths,
                               model_name = model_name,
                               metadata = metadata,
                               quiet = quiet,
                               tar_load_everything = tar_load_everything,
                               .testing = .testing)
cmf_path
}
