#' Loads all specifications executes a model-specifc `targets`
#' pipeline
#'
#' @description `teems_deploy()` creates and executes a
#'   [`targets`](https://books.ropensci.org/targets/) pipeline for all
#'   loaded specifications according to their various path
#'   dependencies. Outputs from [`teems_model()`], [`teems_base()`],
#'   [`teems_param()`], and [`teems_sets()`] are required inputs to
#'   `"model_config"`, `"base_config"`, `"param_config"`, and
#'   `"set_config"` respectively.
#'
#'   Learn more about this function including Tablo file limitations
#'   in `vignette("something")`
#'
#' @inheritParams teems_model
#'
#' @param model_config A list generated by the function
#'   [`teems_model()`].
#' @param base_config A list generated by the function
#'   [`teems_base()`].
#' @param param_config A list generated by the function
#'   [`teems_param()`].
#' @param set_config A list generated by the function
#'   [`teems_sets()`].
#' @param closure_config A list generated by the function
#'   [`teems_closure()`] (default is `NULL`). If `NULL`, a NULL shock
#'   will be executed on the standard closure, effectively returning
#'   the base data. This can be useful for testing purposes or to
#'   return all model coefficient values at the current reference
#'   year.
#' @param time_config A list generated by the function
#'   [`teems_time()`] (default is `NULL`). This argument is only
#'   required in the case of non-static model runs.
#' @param model_name Character of length 1 (default is `"teems"`),
#'   descriptive model name. This string determines the name of
#'   model-specific directory to be written within `"base_dir"` as
#'   well as the `targets` pipeline file that will be run to generate
#'   all input files. Note that to access the `targets` store for a
#'   previously established model, both the `"model_name"` and
#'   `"base_dir"` must remain constant.
#' @param base_dir Character of length 1 (default is `tempdir()`),
#'   directory where the model-specific directory and model pipeline
#'   will be written. If `tempdir()`, the `targets` store and other
#'   model-specific files and directories will not persist across R
#'   sessions. If a persistent directory is specified, some targets
#'   will not need to be rerun in successive R sessions.
#' @param .testing Logical of length 1 (default is `FALSE`), developer
#'   option. If `TRUE`, [`targets::tar_make()`] will be called with
#'   `"callr_function = NULL"`. This allows the model pipeline to be
#'   halted for debugging and/or development purposes through
#'   placement of `browser()`.
#'
#' @importFrom targets tar_helper tar_option_set tar_make
#'   tar_config_set
#'
#' @return File path to a CMF file necessary to execute
#'   [`teems_solve()`].
#'
#' @details `teems_deploy()` consolidates all user inputs and carries
#'   out all operations necessary to run a CGE model. The output file
#'   path serves as a required input to [`teems_solve()`].
#'
#' @seealso [`teems_model()`] for generating the input to
#'   `"model_config"`.
#' @seealso [`teems_base()`] for generating the input to
#'   `"base_config"`.
#' @seealso [`teems_param()`] for generating the input to
#'   `"param_config"`.
#' @seealso [`teems_sets()`] for generating the input to
#'   `"set_config"`.
#' @seealso [`teems_closure()`] for generating the input to
#'   `"closure_config"`.
#' @seealso [`teems_time()`] for generating the input to
#'   `"time_config"`.
#' @seealso [`teems_solve()`] for loading the ouput of this function.
#'
#' @examples
#' \dontrun{
#' # A GTAPv6.2 3-region, 6-sector, 4-endowment static model run with
#' # numeraire shock. Note that the GTAPv7 is currently only
#' # compatible with a separate data format not available in freely
#' # distributed GTAP Databases. Future work will produce a function
#' # to utilize v6.2 data compatible with GTAPv7 and v7 compatible
#' # data with v6.2-based models.
#'
#' v62_model_config <- teems_model(tab_file = "GTAPv62",
#'                                 ndigits = 8,
#'                                 verbose = TRUE)
#'
#' v62_base_config <- teems_base(dat_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' v62_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' v62_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                              region_mapping = "big3",
#'                              sector_mapping = "macro_sector",
#'                              endowment_mapping = "labor_agg",
#'                              verbose = TRUE)
#'
#' v62_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                  type = "uniform",
#'                                  value = 1)
#'
#' v62_closure_config <- teems_closure(shock = v62_numeraire_shk)
#'
#' v62_cmf_path <- teems_deploy(model_config = v62_model_config,
#'                              base_config = v62_base_config,
#'                              param_config = v62_param_config,
#'                              set_config = v62_set_config,
#'                              closure_config = v62_closure_config,
#'                              verbose = TRUE)
#'
#' # A GTAP-INTv1 3-region, 6-sector, 4-endowment, 5 timestep
#' # intertemporal model run with numeraire shock.
#' INTv1_model_config <- teems_model(tab_file = "GTAP-INTv1",
#'                                   ndigits = 8,
#'                                   verbose = TRUE)
#'
#' INTv1_base_config <- teems_base(dat_har = "~/dat/GTAP/v9/2011/gddat.har")
#'
#' INTv1_param_config <- teems_param(par_har = "~/dat/GTAP/v9/2011/gdpar.har")
#'
#' INTv1_set_config <- teems_sets(set_har = "~/dat/GTAP/v9/2011/gdset.har",
#'                                region_mapping = "big3",
#'                                sector_mapping = "macro_sector",
#'                                endowment_mapping = "labor_agg",
#'                                verbose = TRUE)
#'
#' INTv1_numeraire_shk <- teems_shock(var = "pfactwld",
#'                                    type = "uniform",
#'                                    value = 1)
#'
#' INTv1_closure_config <- teems_closure(shock = INTv1_numeraire_shk)
#'
#' INTv1_time_config <- teems_time(time_steps = c(2011, 2012, 2015, 2020, 2030))
#'
#' INTv1_cmf_path <- teems_deploy(model_config = INTv1_model_config,
#'                                base_config = INTv1_base_config,
#'                                param_config = INTv1_param_config,
#'                                set_config = INTv1_set_config,
#'                                closure_config = INTv1_closure_config,
#'                                time_config = INTv1_time_config,
#'                                verbose = TRUE)
#'
#' # In the examples above the `targets` store and model input files
#' # will be written to a per-session temporary folder that will not
#' # persist. In order to fully take advantage of the `targets`
#' # package underpinning `teems`, `"model_name"` and `"base_dir"`
#' # arguments allow for model directories to persist across sessions.
#'
#' custom_path <- teems_deploy(model_config = INTv1_model_config,
#'                             base_config = INTv1_base_config,
#'                             param_config = INTv1_param_config,
#'                             set_config = INTv1_set_config,
#'                             closure_config = INTv1_closure_config,
#'                             time_config = INTv1_time_config,
#'                             model_name = "custom_INT",
#'                             base_dir = path.expand(path = "~"))
#'
#' # Example: Pre-model run directory layout assuming path.expand("~")
#' # evaluates to /home/user
#'
#' #/home/user/custom_INT/
#' #├── custom_INT.R
#' #├── launchpad/
#' #│   ├── basedata.csv
#' #│   ├── custom_INT.cls
#' #│   ├── custom_INT.cmf
#' #│   ├── GTAP-INTv1.tab
#' #│   ├── int_parameters.csv
#' #│   ├── model_diagnostics.txt
#' #│   ├── out/
#' #│   │   ├── coefficients
#' #│   │   ├── variables/
#' #│   │       ├── bin
#' #│   ├── parameters.csv
#' #│   ├── pfa_140725.shf
#' #│   ├── sets.csv
#' #│   ├── time_data.csv
#' #├── store/
#' #│   ├── meta/
#' #│   │   ├── meta
#' #│   │   ├── process
#' #│   │   ├── progress
#' #│   ├── objects/
#' #│   │   ├── base_array
#' #│   │   ├── checked.closure
#' #│   │   ├── checked.set_mappings
#' #│   │   ├── closure
#' #│   │   ├── constructed.shocks
#' #│   │   ├── core_read_files
#' #│   │   ├── CPHI
#' #│   │   ├── endowment_mapping
#' #│   │   ├── expanded.closure
#' #│   │   ├── final.base_tib
#' #│   │   ├── final.closure
#' #│   │   ├── final.par_tib
#' #│   │   ├── final.set_tib
#' #│   │   ├── final.tablo
#' #│   │   ├── init.base_tib
#' #│   │   ├── init.par_tib
#' #│   │   ├── init.set_tib
#' #│   │   ├── int_param
#' #│   │   ├── int_read_files
#' #│   │   ├── internal_tab_file
#' #│   │   ├── KAPPA
#' #│   │   ├── LRORG
#' #│   │   ├── ls_dat
#' #│   │   ├── ls_par
#' #│   │   ├── ls_set
#' #│   │   ├── metadata
#' #│   │   ├── par_array
#' #│   │   ├── parsed.tablo
#' #│   │   ├── precheck.set_mappings
#' #│   │   ├── prepped.base_tib
#' #│   │   ├── prepped.par_tib
#' #│   │   ├── prepped.shocks
#' #│   │   ├── read_files
#' #│   │   ├── region_mapping
#' #│   │   ├── sector_mapping
#' #│   │   ├── set_array
#' #│   │   ├── set_mappings
#' #│   │   ├── shocks
#' #│   │   ├── swap_in
#' #│   │   ├── swap_out
#' #│   │   ├── swapped.in.cls
#' #│   │   ├── swapped.out.cls
#' #│   │   ├── tab_file_check
#' #│   │   ├── tablo_coeff
#' #│   │   ├── tablo_files
#' #│   │   ├── tablo_sets
#' #│   │   ├── tablo_var
#' #│   │   ├── time_coeff
#' #│   │   ├── time_sets
#' #│   │   ├── weighted.par_tib
#' #│   ├── user
#'
#' # Any of the objects above in (/home/user/custom_INT/store/objects)
#' # can be inspected using [`targets::tar_read()`]. For example, the
#' # final model closure:
#' targets::tar_read(name = final.closure,
#'                   store = "/home/user/custom_INT/store")
#' }
#' @export
teems_deploy <- function(model_config,
                         base_config,
                         param_config,
                         set_config,
                         closure_config = NULL,
                         time_config = NULL,
                         model_name = "teems",
                         base_dir = tempdir(),
                         verbose = FALSE,
                         .testing = FALSE)
{
if (missing(x = model_config)) {
  stop("Argument 'model_config' is missing.")
  }
if (missing(x = base_config)) {
  stop("Argument 'base_config' is missing.")
  }
if (missing(x = param_config)) {
  stop("Argument 'param_config' is missing.")
  }
if (missing(x = set_config)) {
  stop("Argument 'set_config' is missing.")
  }
if (missing(x = closure_config)) {
  message("Argument 'closure_config' is missing. A NULL shock and standard closure will be used.")
  }
if (identical(x = model_config[["temporal_dynamics"]], y = "intertemporal")) {
  if (missing(x = time_config)) {
    stop(
      paste(
        "Argument 'time_config' is missing.",
        dQuote(x = "intertemporal"),
        "model runs require time step specifications."
      )
    )
  }
}
if (!identical(x = base_dir, y = tempdir())) {
  base_dir <- path.expand(path = base_dir)
}
model_dir <- file.path(base_dir, model_name)
pipeline_file <- file.path(model_dir, paste0(model_name, ".R"))
store_dir <- file.path(model_dir, "store")
launchpad_dir <- file.path(model_dir, "launchpad")
if (!dir.exists(paths = model_dir)) {
    dir.create(path = model_dir, recursive = TRUE)
  }
if (dir.exists(paths = launchpad_dir)) {
    unlink(x = launchpad_dir, recursive = TRUE, force = TRUE)
  }
dir.create(path = file.path(launchpad_dir, "out", "coefficients"),
           recursive = TRUE)
dir.create(path = file.path(launchpad_dir, "out", "variables", "bin"),
           recursive = TRUE)
tar_model_config <- .model_config(
  config = model_config,
  launchpad_dir = launchpad_dir)
tar_set_config <- .set_config(
  config = set_config,
  temporal_dynamics = model_config[["temporal_dynamics"]],
  full_exclude = model_config[["full_exclude"]],
  write_dir = launchpad_dir)
tar_param_config <- .param_config(
  config = param_config,
  ndigits = model_config[["ndigits"]],
  full_exclude = model_config[["full_exclude"]],
  write_dir = launchpad_dir)
tar_data_config <- .base_config(
  config = base_config,
  ndigits = model_config[["ndigits"]],
  full_exclude = model_config[["full_exclude"]],
  write_dir = launchpad_dir)
tar_time_config <- .time_config(
  config = time_config,
  temporal_dynamics = model_config[["temporal_dynamics"]],
  ndigits = model_config[["ndigits"]],
  write_dir = launchpad_dir)
tar_closure_config <- .closure_config(
  config = closure_config,
  tab_file = model_config[["tab_file"]],
  write_dir = launchpad_dir,
  model_name = model_name)
tar_shock_config <- .shock_config(
  shock = closure_config[["shock"]],
  shock_file = closure_config[["shock_file"]],
  temporal_dynamics = model_config[["temporal_dynamics"]],
  ndigits = model_config[["ndigits"]],
  write_dir = launchpad_dir)
targets <- c(
  tar_model_config,
  tar_set_config,
  tar_param_config,
  tar_data_config,
  tar_time_config,
  tar_closure_config,
  tar_shock_config)
targets::tar_config_set(
  store = store_dir,
  config = file.path(base_dir, "_targets.yaml"),
  project = model_name)
targets::tar_helper(path = pipeline_file, {
  targets::tar_option_set(
    format = "qs",
    memory = "transient",
    garbage_collection = TRUE,
    envir = getNamespace(name = "teems")
  )
  !!targets
})
if (!.testing) {
  targets::tar_make(
    script = pipeline_file,
    store = store_dir)
} else {
  targets::tar_make(
    script = pipeline_file,
    callr_function = NULL,
    store = store_dir)
}
gen_out <- .cmf_write(model_name = model_name,
                      model_dir = model_dir,
                      store_dir = store_dir,
                      launchpad_dir = launchpad_dir)
.pipeline_diagnostics(model_dir = model_dir,
                      launchpad_dir = launchpad_dir,
                      model_name = model_name,
                      store_dir = store_dir,
                      io_files = gen_out[["io_files"]],
                      verbose = verbose)
cmf_path <- gen_out[["cmf_path"]]
cmf_path
}
