#' Load general model specifications
#'
#' @description `teems_model()` loads general model specifications,
#'   conducts pre-pipeline checks, and determines temporal dynamics.
#'   The output of this function is a required input to the
#'   `"model_config"` argument within the [`teems_deploy()`] function.
#'
#'   Learn more about this function including Tablo file limitations
#'   in `vignette("something")`
#'
#' @param tab_file Character of length 1, path to a local Tablo model
#' file or selection of an internal Tablo file. Internally available
#' Tablo files currently include GTAP-INTv1, GTAPv6.2, and GTAPv7.
#' @param model_version Character of length 1 (default is `NULL`),
#'   GTAP model base version corresponding to the selected Tablo model
#'   file. Note that this is distinct from the data format of input
#'   data files. If `NULL`, the first 200 characters of the Tablo file
#'   will be parsed with `model_version` assigned the value following
#'   "Version". Choices:
#'   * `"v6.2"`: Classic GTAP model version 6.2 and models based off
#'   this version. See: https://www.gtap.agecon.purdue.edu/resources/res_display.asp?RecordID=2458
#'   * `"v7.0"`: Standard GTAP model version 7 and models based off this
#'   version. See: https://jgea.org/ojs/index.php/jgea/article/view/47
#' @param ndigits Integer (default is `6`). Exact number of digits to
#'   the right of the decimal point to be written to file for numeric
#'   type double (GEMPack equivalent "real"). This value is passed to
#'   the `format()` nsmall argument and `round()` digits argument.
#' @param full_exclude A character vector. Specifies headers to fully
#'   exclude from all aspects of the model run. Failure to designate
#'   these headers properly will result in errors because some headers
#'   cannot be aggregated or mapped. Modify with caution.
#' @param notes Character string (default is `NULL`). If not `NULL`
#'   notes will be written to a .txt file within the model-specific
#'   directory generated by [`teems_deploy()`].
#' @param data_csv_name Character of length 1 (default is
#'   "basedata.csv"). Name for the core data file that is written as
#'   output.
#' @param parameter_csv_name Character of length 1 (default is
#'   "parameters.csv"). Name for the core parameter file that is
#'   written as output.
#' @param sets_csv_name Character of length 1 (default is "sets.csv").
#'   Name for the core set file that is written as output.
#' @param int_data_csv_name Character of length 1 (default is
#'   "time_data.csv"). Name for the intertemporal data file that is
#'   written as output.
#' @param int_parameter_csv_name Character of length 1 (default is
#'   "int_parameters.csv"). Name for the intertemporal parameter file
#'   that is written as output.
#' @param verbose Logical of length 1 (default is `FALSE`). If `TRUE` output
#'   function-specific diagnostics.
#'
#' @return A list of general model configuration options.
#'
#' @details `teems_model()` return values have no purpose used in
#'   isolation and are rather combined with user inputs in other
#'   `teems` package functions within [`teems_deploy()`] to produce a
#'   path-dependent pipeline resulting in solver-ready input files for
#'   [`teems_solve()`].
#'
#' @seealso [`teems_deploy()`] for loading the output of this
#'   function.
#' @seealso [`teems_time()`] for setting intertemporal configuration
#'   options.
#'
#' @examples
#' # See `vignette("teems-input_files")` for examples and explanation.
#'
#' # Internal Tablo Files
#' # GTAPv6.2 --------------------------------------------------------
#' # When `verbose` == `TRUE`, the detected type of temporal dynamics:
#' # static or intertemporal will be printed to the console.
#' model_config <- teems_model(tab_file = "GTAPv6.2",
#'                             notes = "initial run",
#'                             verbose = TRUE)
#'
#' # Names of output files can be set within this function.
#' model_config <- teems_model(tab_file = "GTAPv6.2",
#'                             data_csv_name = "GTAPDATA.csv",
#'                             parameter_csv_name = "GTAPPARM.csv",
#'                             sets_csv_name = "GTAPSETS.csv")
#'
#' # GTAPv7 ----------------------------------------------------------
#' # Double precision for all non-integer numeric outputs is set here.
#' model_config <- teems_model(tab_file = "GTAPv7",
#'                             ndigits = 12)
#'
#' # GTAP-INTv1 ------------------------------------------------------
#' # An intertemporal model is internally available. For intertemporal
#' # model runs, the `time_config` argument within `teems_deploy()`
#' # will require the return values from `teems_time()`.
#' model_config <- teems_model(tab_file = "GTAP-INTv1",
#'                             note = "10 by 2 year intervals",
#'                             verbose = TRUE)
#'
#' # User-provided Tablo Files ---------------------------------------
#' # Users can provide their own Tablo files. Some Tablo operations
#' # are not supported by the TEEMS solver (see vignnete) and
#' # Tablo-specific idiosyncrasies may not be automatically handled at
#' # the current developmental stage of this package.
#'
#' # User-provided recursive or intertemporal models are unlikely to
#' # run properly at this stage with all package options. For these
#' # and other incompatible models, an `in-situ-solve` option within
#' # (funciton) is currently available.
#' temp_dir <- tools::R_user_dir(package = "teems", "cache")
#' if (!dir.exists(temp_dir)) {
#'   dir.create(temp_dir)
#' }
#' file.copy(from = teems_example(path = "user_model.tab"),
#'           to = temp_dir)
#' path_to_user_model <- file.path(temp_dir, "user_model.tab")
#'
#' print(x = path_to_user_model)
#' head(x = readLines(path_to_user_model))
#' model_config <- teems_model(tab_file = path_to_user_model,
#'                             verbose = TRUE)
#'
#' unlink(x = temp_dir, recursive = TRUE)
#'
#' @export
teems_model <- function(tab_file,
                        model_version = NULL,
                        ndigits = 6,
                        full_exclude = c("DREL", "DVER", "XXCR", "XXCD", "XXCP", "SLUG"),
                        notes = NULL,
                        sets_csv_name = "sets.csv",
                        data_csv_name = "basedata.csv",
                        parameter_csv_name = "parameters.csv",
                        int_data_csv_name = "time_data.csv",
                        int_parameter_csv_name= "int_parameters.csv",
                        verbose = FALSE)
{
fun_call <- match.call()
args_list <- as.list(.match_call(fun_call = fun_call)[-1])
if (missing(x = tab_file))
  {stop(paste("Argument",
              dQuote(x = "tab_file"),
              "is missing!"))
  } else {
if (grepl(pattern = "\\.tab", x = tab_file))
  {args_list[["tab_file"]] <- path.expand(path = tab_file)
    if (!file.exists(tab_file))
      {stop(paste("Filepath for",
                  dQuote(x = "tab_file"),
                  "is not found!"))}
if (any(grepl(pattern = "(intertemporal)",
              x = readLines(con = tab_file))))
  {temporal_dynamics <- "intertemporal"
  } else {
  temporal_dynamics <- "static"}
  } else {
  if (!is.element(el = tab_file, set = names(x = internal_tab)))
    {stop(paste("The chosen internal Tablo file:",
               tab_file,
               "is not supported.",
               "Currently supported Tablo files include:",
               paste(names(x = internal_tab), collapse = ", "),
               'Otherwise an unsupported Tablo file by directly inputting a Tablo path, e.g., "~/path2/tablo.tab"'))
    } else {
      internal_tab <- subset(x = internal_tab,
                             subset = {is.element(el = names(x = internal_tab), set = tab_file)})
      if (any(grepl(pattern = "(intertemporal)", x = internal_tab)))
        {temporal_dynamics <- "intertemporal"
        } else {
         temporal_dynamics <- "static"
        }
      }
    }
  }
if (!is.null(x = model_version)) {
  model_version <- match.arg(arg = model_version,
                             choices = c("v6.2", "v7.0"))
} else {
  model_version <- .get_tab_format(tab_file = tab_file)
  if (!is.element(el = model_version, set = c("v6.2", "v7.0"))) {
    stop("Determined model version does not correspond to either `v6.2` or `v7.0`.",
         "Adjust the header of the Tablo file or explicitly set `model_version`.")
  }

  if (verbose)
  {message(paste("Model version for the provided Tablo file has been determined as:",
                 model_version))}
}
stopifnot(is.numeric(x = floor(x = ndigits)))
if (identical(x = temporal_dynamics, y = "intertemporal"))
  {args_list[["full_exclude"]] <- as.call(x = c(as.list(x = args_list$full_exclude), c("RDLT", "RFLX")))}
if (verbose)
{message(paste("Temporal dynamics have been determined as:",
                temporal_dynamics,
                ifelse(test = identical(x = temporal_dynamics, y = "intertemporal"),
                       yes = paste("\nFor intertemporal model run specifications, see",
                                   dQuote(x = 'help("teems_time")')),
                       no = "")))}
args_list_append <- list(temporal_dynamics = temporal_dynamics)
config <- c(args_list, args_list_append)
config
}
